site_name: sia-cog
site_url: http://www.siadroid.com
site_description: Machine learning and cognitive api.
site_author: Deepak Battini

repo_url: https://github.com/deepakkumar1984/sia-cog

pages:
- Home: index.md
- Machine Learning:
    - Pipeline Components: Machine Learning/__Pipeline Components.md
    - API Guide: Machine Learning/__Usage.md

